svn path=/Zope/trunk/lib/python/zExceptions/; revision=22693
