svn path=/Zope/branches/2.11/lib/python/zExceptions/; revision=110415
