svn path=/Zope/branches/gsoc-python-2.5/lib/python/zExceptions/; revision=91983
